steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pelican-travels', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pelican-travels']
images:
  - 'gcr.io/$PROJECT_ID/pelican-travels'
timeout: '1200s'
